branches:
  only:
    - master

os: Windows Server 2012

init:
  - git config --global core.autocrlf input
  - cinst scriptcs

build_script:
  - C:\Users\appveyor\AppData\Local\scriptcs\scriptcs.exe .\DotNetBuild.Build.ScriptCs.Fluent\build.csx -- target:ci configuration:appveyorConfig
  
test: