branches:
  only:
    - master

os: Windows Server 2012

init:
  - git config --global core.autocrlf input
  - cinst scriptcs -y

build_script:
  - C:\ProgramData\chocolatey\bin\scriptcs.exe .\DotNetBuild.Build.ScriptCs.Fluent\build.csx -- target:ci configuration:appveyorConfig
  
test: off