branches:
  only:
    - master

os: Windows Server 2012

init:
  - git config --global core.autocrlf input
  - cinst scriptcs

build_script:
  - scriptcs .\DotNetBuild.Build.ScriptCs.Fluent\build.csx -- target:ci configuration:defaultConfig